### ISSUE TITLE
npm 으로 설치시 package error 

### ISSUE THREAD

**Issue by bluemir** [bluemir/node-wikinote#59]
편집 화면으로 가면 server 가 아래와 같은 메세지를 표시후 종료
```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module 'ot-text' from '/'
    at /usr/local/lib/node_modules/wikinote/node_modules/browser-resolve/node_modules/resolve/lib/async.js:46:17
    at process (/usr/local/lib/node_modules/wikinote/node_modules/browser-resolve/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/local/lib/node_modules/wikinote/node_modules/browser-resolve/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/local/lib/node_modules/wikinote/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/wikinote/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/wikinote/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqWrap.oncomplete (fs.js:123:15)
```

**Comment by bluemir** [comment]
sharedb의 client code 의 문제인것으로 보임. 

```
b.require("ot-text", {expose: "ot-text"});
```
으로 변경후 실행하였더니 에러 발생하지 않음.

**Comment by bluemir** [comment]
여전히 발생함.. 아마도, 실행시의 경로가 문제인듯 함. npm 으로 설치시에는 browerify 에서 재대로 대응을 하지 못하는듯 함.
